global:
  registry: 635457411372.dkr.ecr.us-east-1.amazonaws.com
  env: staging
frontend:
  replicas: 1
  maxReplicas: 4
  tag: "staging-bae959d4"
book:
  replicas: 1
  maxReplicas: 4
  tag: "staging-bae959d4"
search:
  replicas: 1
  maxReplicas: 4
  tag: "staging-bae959d4"
user:
  replicas: 1
  maxReplicas: 4
  tag: "staging-bae959d4"
postgres:
  host: staging-microservices-postgres.cg9mq6cuoriv.us-east-1.rds.amazonaws.com
  user: bookinguser
ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
pdb:
  maxUnavailable: 1
