global:
  registry: 635457411372.dkr.ecr.us-east-1.amazonaws.com
  env: prod
frontend:
  replicas: 3
  maxReplicas: 10
  tag: "prod-bbed7bda"
book:
  replicas: 3
  maxReplicas: 10
  tag: "prod-118cf47a"
search:
  replicas: 3
  maxReplicas: 10
  tag: "prod-bbed7bda"
user:
  replicas: 3
  maxReplicas: 10
  tag: "prod-bbed7bda"
postgres:
  host: prod-microservices-postgres.cg9mq6cuoriv.us-east-1.rds.amazonaws.com
  user: bookinguser
