name: auth-service-ci

on:
  push:
    branches: [main, develop, 'release/**']
    paths:
      - 'services/auth-service/**'
  pull_request:
    branches: [main]
    paths:
      - 'services/auth-service/**'
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/_reusable-node-ci.yml
    with:
      service-name: auth-service
      service-path: services/auth-service
      ecr-registry: ${{ vars.ECR_REGISTRY }}
      sonar-project-key: skybook-auth-service
      gitops-repo: yourusername/skybook-gitops
      target-env: staging
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      GITOPS_PAT: ${{ secrets.GITOPS_PAT }}