name: booking-service-ci

on:
  push:
    branches: [develop]
    paths:
      - 'services/booking-service/**'
      - '.github/workflows/booking-service-ci.yml'
      - '.github/workflows/_reusable-java-ci.yml'
      - '.github/workflows/_reusable-gitops-promote.yml'
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/_reusable-java-ci.yml
    with:
      service-name: booking-service
      values-key: book
      service-path: services/booking-service
      ecr-registry: ${{ vars.ECR_REGISTRY }}
      sonar-project-key: SurendraKumar17_microservices-ci-platform
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  update-dev-tag:
    needs: ci
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: SurendraKumar17/gitops-k8s-platform
          token: ${{ secrets.GITOPS_PAT }}
          path: gitops-repo

      - name: Install yq
        run: |
          sudo wget -q https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 \
            -O /usr/local/bin/yq && sudo chmod +x /usr/local/bin/yq

      - name: Write real image tag into dev values.yaml
        working-directory: gitops-repo
        run: |
          yq -i '.book.tag = "${{ needs.ci.outputs.image-tag }}"' gitops/environments/dev/values.yaml
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add gitops/environments/dev/values.yaml
          git diff --staged --quiet && echo "Nothing to commit" && exit 0
          git commit -m "gitops(dev): update booking-service tag → ${{ needs.ci.outputs.image-tag }}"
          git push origin main

  promote-staging:
    needs: update-dev-tag
    uses: ./.github/workflows/_reusable-gitops-promote.yml
    with:
      service-name: booking-service
      values-key: book
      gitops-repo: SurendraKumar17/gitops-k8s-platform
      source-env: dev
      target-env: staging
    secrets:
      GITOPS_PAT: ${{ secrets.GITOPS_PAT }}
      ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN }}

  promote-prod:
    needs: promote-staging
    uses: ./.github/workflows/_reusable-gitops-promote.yml
    with:
      service-name: booking-service
      values-key: book
      gitops-repo: SurendraKumar17/gitops-k8s-platform
      source-env: staging
      target-env: prod
      # Staging pods are intentionally not running right now (no dedicated staging DB —
      # shared-DB setup deferred). Re-enable once bookmytrip-staging is healthy again:
      # argocd-app-name: bookmytrip-staging
      # argocd-server: http://k8s-argocd-argocdin-860d4e6d33-540967312.us-east-1.elb.amazonaws.com
    secrets:
      GITOPS_PAT: ${{ secrets.GITOPS_PAT }}
      ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN }}