name: notification-service-ci

on:
  push:
    branches: [develop]
    paths:
      - 'services/notification-service/**'
  pull_request:
    branches: [develop]
    paths:
      - 'services/notification-service/**'
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/_reusable-node-ci.yml
    with:
      service-name: notification-service
      values-key: notification
      service-path: services/notification-service
      ecr-registry: ${{ vars.ECR_REGISTRY }}
      sonar-project-key: SurendraKumar17_Production-Grade-Microservices-on-Kubernetes
      gitops-repo: SurendraKumar17/microservices-cd-platform
      target-env: dev
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      GITOPS_PAT: ${{ secrets.GITOPS_PAT }}